package com.jobportal.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    CANDIDATE_SHORTLISTED,
    CANDIDATE_REJECTED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CANCELLED,
    JOB_POSTED,
    SYSTEM_ALERT
}
